Create distribution_lib for TF backend
keras-team/keras-core pull request #890
Opened 2023-09-14 23:55 UTC by hubingallin

* Add Mesh and Layout helper functions

2023-09-18 21:56 UTC, qlzh727 commented on keras_core/distribution/distribution_lib_test.py
> +
Probably for a future task, we might want to split the backend specific tests into separate files.

2023-09-18 21:56 UTC, qlzh727 commented on keras_core/distribution/distribution_lib_test.py
> +        devices = [f"CPU:{i}" for i in range(8)]
Thanks for catching this, we might want to fix this for test_input_validation as well.

2023-09-18 21:56 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +    return dtensor.local_devices(device_type=device_type)
This seems only return the local devices, which is different from the docstring.

2023-09-18 21:56 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +        A `dtensor.Mesh` instance.
let's use the full tf API name for type annotation, eg `tf.dtensor.Mesh`.

2023-09-18 21:56 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +        A `dtensor.Layout` instance.
Same here.

2023-09-18 22:44 UTC, qlzh727 commented
Please also fix the code format via keras_core/shell/{lint|format}.sh

2023-09-19 23:19 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +    return dtensor.local_devices(device_type=device_type)
Seems that this is not addressed, did I miss anything?

2023-09-20 21:50 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +    return tf.config.list_logical_devices(device_type=device_type)
I think this might not be correct. It probably should map to https://www.tensorflow.org/api_docs/python/tf/experimental/dtensor/Mesh#global_devices.

2023-09-20 21:50 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +    return dtensor.create_mesh(
I think the usage of create_mesh will limit it to be a single worker mesh. We might want to use the create_distributed_mesh https://www.tensorflow.org/api_docs/python/tf/experimental/dtensor/create_distributed_mesh

2023-09-21 19:40 UTC, qlzh727 commented on keras_core/backend/tensorflow/distribution_lib.py
> +    return tf.config.list_logical_devices(device_type=device_type)
Chatted offline. let's include some context here as comment for why we have local device here.

2023-09-21 23:18 UTC, qlzh727 approved these changes

2023-09-22 16:32 UTC, qlzh727 commented
The unit tests are failing. Please check.

2023-09-22 16:33 UTC, qlzh727 requested changes
Please fix the unit test.

2023-09-22 19:17 UTC, fchollet commented
Keras Core is becoming Keras 3, and we're switching development to the main repository! Please reopen this PR in the [keras-team/keras](https://github.com/keras-team/keras) repository. Unfortunately we aren't able to automatically transfer PRs (but we have transferred all issues).

2023-09-22 19:17 UTC, closed without merging